# Generated by Django 4.1.7 on 2023-02-22 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_title', models.CharField(max_length=256, primary_key=True, serialize=False, unique=True, verbose_name='title')),
            ],
        ),
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
                ('url', models.CharField(default='#', max_length=256)),
                ('menu_title', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='menu.menu')),
            ],
        ),
    ]
